FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update --fix-missing 

RUN apt-get install -y wget python3 python3-pip build-essential cmake pkg-config libx11-dev libatlas-base-dev libgtk-3-dev libboost-python-dev tzdata python-opencv && \
        dpkg-reconfigure --frontend noninteractive tzdata

RUN mkdir -p /src

WORKDIR /src

ADD requirements.txt /src/requirements.txt
RUN pip3 install -r requirements.txt

ADD color_transfer /src/color_transfer

ADD app.py /src/app.py

EXPOSE 5000

ENTRYPOINT ["python3"]

CMD ["app.py"]
